#define PROGNAME "privatetcp"
#define MAX_BACKLOG 5
#define MAX_CLIENTS 5
#define MIN_CLIENT_UID 1000
#define MAX_CLIENT_UID 32766
#define NOBODY_UID 32767
#define NOBODY_GID 32767
#define NOBODY_DIR "/var/empty"
#define CLIENT_PATH "/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin"
